import Head from "next/head";
import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";
import SectionCards from "../components/card/section-cards";
import { getPopularVideos, getVideos } from "../lib/videos";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  const disneyVideos = await getVideos("disney trailer");
  // const productivityVideos = await getVideos("productivity");
  // const travelVideos = await getVideos("travel");
  // const popularVideos = await getPopularVideos();

  return {
    props: { disneyVideos },
  };
}

export default function Home(props) {
  const { disneyVideos, travelVideos, productivityVideos, popularVideos } =
    props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavBar username="yazdun@email.com" />
        <Banner
          videoId={1}
          title="Clifford the red dog"
          subTitle="a very cute dog"
          imgUrl="/static/clifford.webp"
        />
        <SectionCards title="Disney" videos={disneyVideos} />
      </main>
    </div>
  );
}
